columns = {
    "first_name": "First name",
    "last_name": "Last name",
    "birthday": "Birthday",
    "gender": "Gender",
    "country": "Country",
    "q1" : "Are you willing to be a team leader on your team?", 
    "q2" : "Would you consider yourself a creative thinker?",
    "q3" : "Do you consider yourself knowledgable about the Bible?",
    "q4" : "Are you physically fit and able to play in outdoor activities like outdoor games, obstacle courses, running, sport etc.?",
    "q5" : "Can you play the guitar, piano or keyboard well?",
    "q6" : "Have you been in a Christian camp before?",
    "q7" : "Will you be able to create and design costumes and props for the drama?",
    "q8" : "Will you be able to create and design costumes and props for the drama?",
    "q9" : "Are you entitled to be in the team with someone, please write their full name - Example kids needs to be with the parent/guardian or new camper wants to be with someone they know. Leave blank for no.", 
    "q10" : "Please list the full names of people who should not be on your team (e.g., spouse, siblings, best friends, people I see (almost) every day). This will help us create teams that encourage meeting new people, fostering new connections, and promoting teamwork with a more diverse group. Being on a team with familiar faces can limit these opportunities.",
}
